color0 #151312
color1 #ffb4ab
color2 #dbc1bb
color3 #d2c3c1
color4 #cfc6b0
color5 #dbc1bb
color6 #d2c3c1
color7 #e7e1e0
color8 #9b8e8b
color9 #ffb4ab
color10 #dbc1bb
color11 #d2c3c1
color12 #cfc6b0
color13 #dbc1bb
color14 #d2c3c1
color15 #e7e1e0

cursor                #e7e1e0
cursor_text_color     #151312
background            #151312
foreground            #e7e1e0
selection_foreground  #d2c3c0
selection_background  #4f4442
active_border_color   #dbc1bb
inactive_border_color #4f4442
url_color             #dbc1bb

active_tab_foreground   #3d2c29
active_tab_background   #dbc1bb
inactive_tab_foreground #d2c3c0
inactive_tab_background #4f4442
cursor_trail_color      #d2c3c0
